export enum ChatEvent {
	Ban = 'ban',
	Join = 'join',
	Kick = 'kick',
	Mute = 'mute',
	Block = 'block',
	Leave = 'leave',
	Create = 'create',
	Demote = 'demote',
	Invite = 'invite',
	Message = 'message',
	Promote = 'promote',
	Unblock = 'unblock',
	DirectMessage = 'dm',
	UserList = 'userList',
	MessageHistory = 'history',
	ChannelList = 'channelList',
	BlockedUsersList = 'blockList',
	UpdateChannel = 'updateChannel',
	JoinedChannels = 'joinedChannels',
  }
  