version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgres://postgres:your_password_here@postgres:5432/ft_transcendence
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    depends_on:
      - api