version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ft_transcendence
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ft_transcendence
    depends_on:
      - postgres
    volumes:
      - backend_data:/backend
    ports:
      - 8080:8080
      - 5555:5555
      - 3333:3333

volumes:
  db_data:
    name: db_data
  backend_data:
    name: backend_data

networks:
  ft_transcendence:
    driver: bridge
