name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
      - ci_implementation_nico
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose version

    - name: Build and Deploy with Docker Compose
      run: docker-compose up -d

    # - name: Test the deployed service (adjust as needed)
    #   run: docker-compose exec your-service-name sh -c "your-test-command"

    - name: Clean up
      run: docker-compose down
