name: Build backend

on:
  pull_request:
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Spécifiez la version de Node.js que vous utilisez dans votre projet
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Generate prisma client
        run: npx prisma generate
      
      - name: Build
        run: npm run build  # Assurez-vous que votre script de build est correctement défini dans votre fichier package.json
