jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Backend
        run: |
          cd backend
          npm install

      - name: Run Prisma Migrations
        run: |
          cd backend
          ./backend.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend (Example: Deploy to AWS Elastic Beanstalk)
        run: |
          cd backend
          npm run deploy