name: Docker Image CI

on:
  push:
    branches: [ "main", "ci_implementation_nico" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: make